#!/bin/bash
PROTO_EXTPATH="/opt/imply/extensions/druid-protobuf-extensions"
mkdir -p ${PROTO_EXTPATH}
cd ${PROTO_EXTPATH} 
curl -O -L https://packages.confluent.io/maven/io/confluent/kafka-protobuf-provider/6.0.1/kafka-protobuf-provider-6.0.1.jar
curl -O -L https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib/1.4.0/kotlin-stdlib-1.4.0.jar
curl -O -L https://repo1.maven.org/maven2/com/squareup/wire/wire-schema/3.2.2/wire-schema-3.2.2.jar

